### ISSUE TITLE
Crash on big folders

### ISSUE THREAD

**Issue by jlelse** [afollestad/impression#300]
The app crashes on folders with a big number of photos inside (~1500)

**Comment by plusCubed** [comment]
Is this using the latest repo code or the last apk?

**Comment by jlelse** [comment]
Latest repo code

**Comment by plusCubed** [comment]
Got it. I'll take a look, haven't tested with that large of an amount of pictures (up to 500 works for me). Do you have a stack trace of the crash?

**Comment by jlelse** [comment]
Not yet. But next time I'm on my PC Ill test again and post stacktrace

**Comment by jlelse** [comment]
It happens when opening an Image from large folders
My forks application id is jlelse.impress but I have same repo code

```
11-30 07:02:28.385 1061-1148/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
11-30 07:02:28.386 1061-1148/? W/ActivityManager: Exception in new application when starting activity jlelse.impress.debug/com.afollestad.impression.viewer.ViewerActivity
                                                  android.os.TransactionTooLargeException
                                                      at android.os.BinderProxy.transactNative(Native Method)
                                                      at android.os.BinderProxy.transact(Binder.java:496)
                                                      at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:807)
                                                      at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1221)
                                                      at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:578)
                                                      at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6168)
                                                      at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6234)
                                                      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:488)
                                                      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2315)
                                                      at android.os.Binder.execTransact(Binder.java:446)
11-30 07:02:28.387 1061-1148/? A/ActivityManager: Exception thrown launching activities in ProcessRecord{31b89b35 8844:jlelse.impress.debug/u0a204}
                                                  android.os.TransactionTooLargeException
                                                      at android.os.BinderProxy.transactNative(Native Method)
                                                      at android.os.BinderProxy.transact(Binder.java:496)
                                                      at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:807)
                                                      at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1221)
                                                      at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:578)
                                                      at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6168)
                                                      at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6234)
                                                      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:488)
                                                      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2315)
                                                      at android.os.Binder.execTransact(Binder.java:446)
```

I think it's a bug in the ViewerActivity where all images are preloaded for the viewpager

**Comment by plusCubed** [comment]
Reproduced. Initial research basically says everything's limited to 1MB in `Parcelable` transactions, and `Serializable` doesn't have that problem. I originally switched to `Parcelable` because it's supposed to be faster, but after this and a whole bunch of other weird bugs/quirks I've encountered already, it's probably best to switch back.

Or the current entries could just be stored in a singleton. That comes with its own host of other problems though, but it means no serializing and deserializing. I'll stick with `Serializable` for now, and if needed I'll consider switching later.

**Comment by plusCubed** [comment]
Hmm.. `Serializable` doesn't work either, which makes sense. I don't know why I thought they would be different when they're all going through an Intent, which is the thing that has the size limit. I'll try structuring around a Singleton then.

**Comment by jlelse** [comment]
Ok seems to be logical

**Comment by jlelse** [comment]
Isn't there an alternative for intent extras?

**Comment by jlelse** [comment]
@plusCubed Does the latest commit fix the bug?
